[tool.black]
line-length = 90
skip-string-normalization = true
exclude = '''
/(
    venv
  | pruebas
  | reports
  | \.git
  | \.mypy_cache
  | __pycache__
  )/
'''

[tool.isort]
profile = "black"
line_length = 90
multi_line_output = 3
include_trailing_comma = true
skip = ["venv", "pruebas", "reports", "__pycache__"]
